- hosts: all
  roles:
    - role: gantsign.visual-studio-code
    - role: andrewrothstein.anaconda
    - role: dochang.docker
  tasks:
  - name: install the latest version of NodeJS
    dnf:
      name: nodejs
      state: latest
    become: yes