---
- hosts: all
  become: yes

  pre_tasks:
  - name: Install libselinux-python
    dnf:
      name: libselinux-python
      state: latest
    
  roles:
    - role: gantsign.visual-studio-code
    - role: andrewrothstein.anaconda
    - role: dochang.docker

  tasks:
  - name: install packages for dev
    dnf:
      name: {{item}}
      state: latest
    with_items:
      - nodejs
    become: yes
  
  - name: Install packages for photo
    dnf: 
      name: {{item}} 
      state: latest
    with_items:
      - krita
      - rawtherapee
      - darktable
    become: yes
